version: '3.8'

services:
  # SQL Server service
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123
      - MSSQL_PID=Express
    ports:
      - "1431:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - spring-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  # Spring Boot application
  app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://db:1433;databaseName=gdgt_project;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.SQLServerDialect
      - SERVER_PORT=8080
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge

volumes:
  mssql-data: